SELECT SUM(A.COUNT * B.COUNT) FROM (
	SELECT 'Q' AS DOCID, 'washington' AS TERM, 1 AS COUNT
	UNION
	SELECT 'Q' AS DOCID, 'taxes' AS TERM, 1 AS COUNT
	UNION
	SELECT 'Q' AS DOCID, 'treasury' AS TERM, 1 AS COUNT
) A 
JOIN 
(
	SELECT * FROM FREQUENCY
	UNION
	SELECT 'Q' AS DOCID, 'washington' AS TERM, 1 AS COUNT
	UNION
	SELECT 'Q' AS DOCID, 'taxes' AS TERM, 1 AS COUNT
	UNION
	SELECT 'Q' AS DOCID, 'treasury' AS TERM, 1 AS COUNT
) B ON A.TERM = B.TERM WHERE A.DOCID = 'Q' GROUP BY A.DOCID, B.DOCID ORDER BY SUM(A.COUNT * B.COUNT) DESC LIMIT 1;
